# Generated by Django 2.2.9 on 2020-01-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_dummy_data",
                    models.BooleanField(
                        default=False,
                        verbose_name="Instance was generated as dummy data",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="First name of the author",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        max_length=200,
                        verbose_name="Middle name(s) of the author",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=200, verbose_name="Last name of the author"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_dummy_data",
                    models.BooleanField(
                        default=False,
                        verbose_name="Instance was generated as dummy data",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Name of the journal"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_dummy_data",
                    models.BooleanField(
                        default=False,
                        verbose_name="Instance was generated as dummy data",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Name of the publisher"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="City the publisher is located in",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_dummy_data",
                    models.BooleanField(
                        default=False,
                        verbose_name="Instance was generated as dummy data",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=400, verbose_name="Title of the source"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("AR", "Article"), ("BK", "Book")],
                        default="AR",
                        max_length=2,
                        verbose_name="Type of the source",
                    ),
                ),
                (
                    "year_of_publication",
                    models.IntegerField(
                        verbose_name="Publisher of the source"
                    ),
                ),
                (
                    "journal_page_range_start",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Index of the journal page where the article begins.",
                    ),
                ),
                (
                    "journal_page_range_end",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Index of the journal page where the article ends.",
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="sources",
                        to="database.Author",
                        verbose_name="Authors of the source",
                    ),
                ),
                (
                    "source_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.Journal",
                        verbose_name="Journal the source was published in (if applicable)",
                    ),
                ),
                (
                    "source_publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="database.Publisher",
                        verbose_name="Publisher of the source (if applicable)",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_dummy_data",
                    models.BooleanField(
                        default=False,
                        verbose_name="Instance was generated as dummy data",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cited",
                        to="database.Source",
                        verbose_name="The source being referred to ('TO')",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="database.Source",
                        verbose_name="The source making the reference ('FROM')",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="journal",
            name="journal_publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journals",
                to="database.Publisher",
                verbose_name="Publisher of the journal",
            ),
        ),
    ]
