# Generated by Django 2.2.9 on 2020-01-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="year_of_publication",
            field=models.IntegerField(
                verbose_name="Year the source was published"
            ),
        ),
    ]
